server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
    instance-id: eureka-client1
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8081/eureka/,http://eurekaserver2.com:8082/eureka/


spring:
  application:
    name: eureka-client
  datasource:
    dynamic:
      primary: one
      mp-enabled: true
      datasource:
#        master:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#          username: root
#          password: admin
#          type: com.alibaba.druid.pool.DruidDataSource
#        slaves:
          one:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
            username: root
            password: admin
            type: com.alibaba.druid.pool.DruidDataSource
          two:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/user2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
            username: root
            password: admin
            type: com.alibaba.druid.pool.DruidDataSource
          three:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/user3?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
            username: root
            password: admin
            type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

logging:
  level:
    com.example.eurekaclient.mapper : debug