
server:
  port: 8082

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaserver1.com:8081/eureka/
  instance:
    hostname: eurekaserver2.com