
server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaserver2.com:8082/eureka/
  instance:
    hostname: eurekaserver1.com