
server:
  port: 7072

eureka:
  instance:
    prefer-ip-address: true
    instance-id: eureka-sumer2
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8081/eureka/,http://eurekaserver2:8082/eureka/

spring:
  application:
    name: eureka-sumer2

feign:
  hystrix:
    enabled: false