server:
  port: 7072

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8081/eureka/,http://eurekaserver2:8082/eureka/
  instance:
    prefer-ip-address: true
    instance-id: eureka-sumer2


spring:
  application:
    name: eureka-sumer2
#  cloud:
#    bus:
#      trace:
feign:
  hystrix:
    enabled: true
#        enabled: true