server:
  port: 9091

spring:
  application:
    name: eureka-client

eureka:
  instance:
    instance-id: eureka-client2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8081/eureka/,http://eurekaserver2.com:8082/eureka/